version: '3.8'

services:
  springboot-app:
    build: .
    container_name: springboot-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database-host:5432/payment
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=abc123
    ports:
      - "8080:8080"
    depends_on:
      - database-host

  database-host:
    image: postgres:13
    container_name: postgres-db
    environment:
      - POSTGRES_DB=payment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abc123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
    driver: local
